---
title: Contrastes de hipótesis paramétricos
lang: es
---



:::{#exr-contraste-media-consumo-azucar}
Sabiendo que el año pasado el consumo per cápita de azúcar en España fue de $4.8$ kg y que este consumo sigue una distribución normal, hemos seleccionado aleatoriamente a $20$ españoles obteniendo una media muestral de $5$ kg y una cuasidesviación típica muestral de $0.4$ kg. Contrastar la hipótesis de que el consumo de azúcar per cápita de este año en España no ha variado utilizando un nivel de significación del $10$% en cada uno de los casos siguientes.

a. Suponiendo que la alternativa es que el consumo de azúcar per cápita sea distinto.

b. Suponiendo que la alternativa es que el consumo de azúcar per cápita sea mayor.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X\sim N(\mu,\sigma)$ la variable aleatoria que mide el consumo per cápita de azúcar en España.

a. La hipótesis nula es $H_0: \mu=4.8$ y la hipótesis alternativa es $H_1: \mu\neq 4.8$. Utilizando el contraste de la t de student, el estadístico de contraste es $t=2.24$ y el p-valor es $p =2 P(t(19)>2.24) = 0.037$. Como el p-valor es menor que el nivel de significación $\alpha = 0.1$, se rechaza la hipótesis nula y se concluye que el consumo de azúcar per cápita de este año en España ha variado.

a. En este caso, la hipótesis nula es $H_0: \mu=4.8$ y la hipótesis alternativa es $H_1: \mu> 4.8$. El estadístico del contraste es el mismo pero ahora el p-valor es $p = P(t(19)>2.24) = 0.0185$. Como el p-valor es menor que el nivel de significación $\alpha = 0.1$, se rechaza la hipótesis nula y se concluye que el consumo de azúcar per cápita de este año en España ha aumentado.
:::


:::{#exr-contraste-proporcion-asistencia-clase}
En una clase de Estadística se ha comprobado que el $20$% del alumnado falta a clase. Para disminuir esta preocupante cifra, los profesores han incorporado un sistema de evaluación continua que tendrá en cuenta las notas de clase de los alumnos en la nota final. Contraste con un nivel de significación del $5$% que la incorporación de este método no es efectiva, es decir, el absentismo antes y después de la evaluación continua es el mismo, sabiendo que el porcentaje medio de no asistencia en $50$ días tomados al azar ha sido del $17$%.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X\sim B(50,p)$ la variable aleatoria que mide el número de días que falta un alumno a clase. La hipótesis nula es $H_0: p=0.2$ y la hipótesis alternativa es $H_1: p\neq 0.2$. Utilizando el contraste para la proporción de una población, el estadístico de contraste es $z=-1.5$ y el p-valor es $p =2 P(Z<-0.53) = 0.298$. Como el p-valor es mayor que el nivel de significación $\alpha = 0.05$, no se rechaza la hipótesis nula y se concluye que la incorporación de este método no es efectiva.
:::

:::{#exr-contraste-media-detergente}
Una empresa fabricante de detergente afirma que el contenido de cada paquete de detergente sigue una distribución normal de media $2150$ g, pero una Asociación de Consumidores no está conforme con esta afirmación, por lo que realiza un estudio consistente en obtener una muestra aleatoria simple de $121$ paquetes de detergente, obteniendo un contenido medio muestral de $2070$ g y una cuasidesviación típica muestral de $130$ grs. Contraste esta hipótesis con un nivel de significación del $5$%.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X\sim N(\mu,\sigma)$ la variable aleatoria que mide el contenido de cada paquete de detergente. La hipótesis nula es $H_0: \mu=2150$ y la hipótesis alternativa es $H_1: \mu\neq 2150$. Utilizando el contraste de la t de student, el estadístico de contraste es $t=-6.77$ y el p-valor es $p =2 P(t(120)<-6.77) = 0.00005$. Como el p-valor es menor que el nivel de significación $\alpha = 0.05$, se rechaza la hipótesis nula y se concluye contenido promedio de los paquetes de detergente es significativamente diferente de los $2150$ g declarados por la empresa.
:::

:::{#exr-contraste-proporcion-aprobados}
El número de aprobados en una asignatura de un determinado curso ha sido del $64$%. En uno de los grupos de ese curso se han presentado al examen $40$ alumnos de los que $31$ aprobaron. ¿Puede afirmarse con un nivel de significación del $5$% que los alumnos de dicho grupo han obtenido mejores calificaciones que el resto de los alumnos del curso?
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X\sim B(40,p)$ la variable aleatoria que mide el número de aprobados en el grupo. La hipótesis nula es $H_0: p=0.64$ y la hipótesis alternativa es $H_1: p> 0.64$. Utilizando el contraste para la proporción de una población, el estadístico de contraste es $z=1.78$ y el p-valor es $p = P(Z>1.78) = 0.0376$. Como el p-valor es menor que el nivel de significación $\alpha = 0.05$, se rechaza la hipótesis nula y se puede afirmar que los alumnos de dicho grupo han obtenido mejores calificaciones que el resto de los alumnos del curso.
:::

:::{#exr-contraste-media-consumo}
Se sabe que el consumo anual de helado correspondiente a cada español sigue una distribución normal y que el año pasado el consumo medio fue de 20 kg.  Queremos contrastar si este año se va a mantener el consumo medio de helado que el año pasado, y para comprobarlo se efectúa una muestra aleatoria de 22 españoles, obteniéndose los siguientes resultados: 

<div style="text-align: center">
15, 18, 24, 31, 22, 12, 6, 35, 42, 2, 16, 25, 20, 10, 17, 19, 14, 30, 14, 23, 15, 19.
</div>

Realizar el contraste con un nivel de significación de 0.10.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X\sim N(\mu,\sigma)$ la variable aleatoria que mide el consumo anual de helado correspondiente a cada español. La hipótesis nula es $H_0: \mu=20$ y la hipótesis alternativa es $H_1: \mu\neq 20$. Utilizando el contraste de la t de student, el estadístico de contraste es $t=-0.25$ y el p-valor es $p =2 P(t(21)<-0.25) = 0.8033$. Como el p-valor es mayor que el nivel de significación $\alpha = 0.1$, no se rechaza la hipótesis nula y se concluye que no hay pruebas evidentes en la muestra de que el consumo de helados este año vaya a ser diferente del año pasado.
:::

:::{#exr-contraste-varianza-telefonica}
Telefónica ha constatado que el consumo de datos de los clientes que han contratado el paquete Fusión (fibra simétrica, TV, teléfono fijo y móvil. sigue una distribución normal cuya dispersión viene determinada por $\sigma$=$3$ Gb. Sin embargo, tras la incorporación de Netflix a la oferta de Movistar TV se ha observado que la dispersión habría podido cambiar, por lo que se ha llevado a cabo un muestreo con $15$ clientes en el que la cuasidesviación típica es igual a $3.5$ Gb.

Determine si efectivamente la varianza en el consumo de datos de los clientes Fusión ha cambiado tras la incorporación de Netflix y especifique la región crítica óptima utilizando un nivel de significación del $2$%.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X\sim N(\mu,\sigma)$ la variable aleatoria que mide el consumo de datos de los clientes que han contratado el paquete Fusión. La hipótesis nula es $H_0: \sigma^2=9$ y la hipótesis alternativa es $H_1: \sigma^2\neq 9$. Utilizando el contraste de la $\chi^2$, el estadístico de contraste es $\chi^2=19.06$ y para un nivel de significación $\alpha = 0.02$, se obtienen las regiones críticas delimitadas por $\chi^2_{14}(0.01) = 5.629$ y $\chi^2_{14}(0.99) = 26.119$. Como el estadístico del contraste cae entre estos dos valores,  dentro de la región de aceptación, no se rechaza la hipótesis nula y se concluye que no hay pruebas evidentes en la muestra de que la varianza en el consumo de datos de los clientes Fusión haya cambiado tras la incorporación de Netflix.
:::

:::{#exr-contraste-media-peso}
La OMS está preocupada por el incremento de la obesidad entre los niños de $12$ años. La variable peso de los niños se distribuye según una normal. El equipo formula la hipótesis de que el peso medio de los niños de $12$ años es de $46.5$ kg. Seleccionada una muestra aleatoria de $40$ niños, se obtiene que la media muestral es $49$ kg y la cuasidesviación típica muestral vale $7$ kg.

a.  Realizar el contraste de hipótesis adecuado para ver si el peso medio de los niños de $12$ años es mayor de $46.5$ kg.

a.  Si se pretende detectar al menos un incremento de $2$ kg en el peso medio de los niños de $12$ años, ¿qué potencia tiene el contraste?

a.  ¿Qué tamaño muestral sería necesario para conseguir una potencia del al menos el $80$%?
:::

:::{.callout-tip collapse="true"}
## Solución

Sea $X\sim N(\mu,\sigma)$ la variable aleatoria que mide el peso de los niños de $12$ años.

a.  La hipótesis nula es $H_0: \mu=46.5$ y la hipótesis alternativa es $H_1: \mu> 46.5$. Utilizando el contraste de la t de student, el estadístico de contraste es $t=2.26$ y el p-valor es $p = P(t(39)>2.26) = 0.0147$. Como el p-valor es menor que el nivel de significación $\alpha = 0.05$, se rechaza la hipótesis nula y se concluye que el peso medio de los niños de $12$ años es mayor de $46.5$ kg.

b.  Cuando hay un incremento de al menos $2$ kg en el peso medio de los niños el estadístico del contraste es $t=1.81$, y la potencia del contraste es $1-P(t(39)<1.81) = 0.039$. Esta potencia es muy baja, lo cual indica que es poco probable que esta prueba detecte una diferencia de ese tamaño si realmente existe.

c.  Para conseguir una potencia del al menos el $80$% se necesita un tamaño muestral de $n=76$ niños.
:::

:::{#exr-contraste-proporcion-consumo-producto}
Al lanzar un nuevo producto al mercado, el fabricante duda entre que sea adquirido por el 20% de la población o que sea adquirido por el 30%. Seleccionada al azar una muestra de 400 posibles compradores del producto se obtiene que la demandaría el 22%. La regla de decisión que utilizaremos es aceptar la hipótesis nula si adquieren el producto menos del 25% de los consultados.

a. ¿Se puede aceptar la hipótesis nula?

b. Calcular nivel de significación del contraste.

c. Obtener la potencia del contraste.
:::

:::{.callout-tip collapse="true"}
## Solución

Sea $X\sim B(400,p)$ la variable aleatoria que mide el número de compradores del producto. 

a.  La hipótesis nula es $H_0: p=0.2$ y la hipótesis alternativa es $H_1: p> 0.2$. Si se decide fijar aceptar la hipótesis nula con una proporción muestral menor de $0.25$ entonces se aceptaría la hipótesis ya que la proporción muestral observada es $0.22$.

b.  El nivel de significación del contraste es la máxima probabilidad de cometer un error de tipo I, es decir, de rechazar la hipótesis nula cuando es cierta, que en este caso es $P(\hat p>0.25|p=0.2) = 0.0062$.

c.  La potencia del contraste es $1-P(\hat p<0.25|p=0.3) = 0.985$, por lo que se trata de un buen contraste para detectar al menos un incremento del $10$% en la proporción de compradores.
:::

:::{#exr-contraste-media-consumo-electrico}
Según los datos publicados por REE (Red Eléctrica Española. el consumo medio diario de electricidad en los hogares españoles es de $9.5$ watios/hora. La compañía comercializadora de electricidad Holaluz sabe que el citado consumo sigue una distribución normal, pero debe determinar cuál será el consumo medio en el que basará su estrategia de cara a 2021, ya que el aumento del teletrabajo podría provocar que el referido consumo medio varíe en el nuevo ejercicio y se incremente a $11$ watios/hora, por lo que ha llevado a cabo un muestra aleatoria con $50$ clientes en el que la media muestral ha resultado ser igual a un consumo de $10.57$ watios/hora mientras que la cuasivarianza es igual a $9$.

a. ¿Con que hipótesis debería trabajar Holaluz en 2021 si se considera un nivel de significación del $1$%?

b. ¿Cuál es la potencia del contraste?
:::

:::{.callout-tip collapse="true"}
## Solución
a.  Sea $X\sim N(\mu,\sigma)$ la variable que mide el consumo diario de electricidad de los hogares españoles. 

La hipótesis nula es $H_0: \mu=9.5$ y la hipótesis alternativa es $H_1: \mu> 9.5$. 

Utilizando el contraste de la t de student, el estadístico de contraste es $t=2.522$ y el p-valor es $p = P(t(49)>2.522) = 0.0075$. Como el p-valor es menor que el nivel de significación $\alpha = 0.01$, se rechaza la hipótesis nula y se concluye que el consumo medio de electricidad en los hogares españoles en 2021 será mayor de $9.5$ watios/hora.

a.  Suponiendo que la media del consumo es $11$, el estadístico del contraste es $t = 3.536$ y la potencia del contraste suponiendo que el consumo medio es $11$ watios/hora, es $0.965$.
:::

:::{#exr-contraste-media-emision-CO2}
Se ha desarrollado un aditivo para gasolina que reduce la emisión de CO en la combustión.
Para comprobar la efectividad del aditivo, se realiza un estudio en el que se mide en una muestra de 10 coches la
cantidad de CO₂ emitida (en Kg/l), tanto con gasolina con aditivo, como con gasolina sin aditivo, obteniendo los
siguientes resultados:

$$
\begin{array}{rcccccccccc}
\hline
\mbox{Sin aditivo:}  & 0.38 & 0.42 & 0.41 & 0.39 & 0.45 & 0.47 & 0.44 & 0.38 & 0.40 & 0.50  \\
\mbox{Con  aditivo:} & 0.38 & 0.36 & 0.38 & 0.32 & 0.39 & 0.45 & 0.39 & 0.39 & 0.35 & 0.48 \\
\hline
\end{array}
$$

Realizar un contraste de hipótesis para comprobar la efectividad del aditivo.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X\sim N(\mu,\sigma)$ la variable aleatoria que mide la diferencia entre la cantidad de CO₂ emitida en la combustión de la gasolina sin aditivo y con aditivo. La hipótesis nula es $H_0: \mu = 0$ y la hipótesis alternativa es $H_1: \mu>0$. 

Utilizando el contraste de la t de student para la comparación de medias en poblaciones pareadas, el valor crítico que define las regiones de aceptación y rechazo para $\alpha=0.05$ es $t^9_{0.95}=1.833$. El estadístico del contraste es $t=4.072$ que claramente cae en la región de rechazo al ser mayor que el valor crítico, y el p-valor es $p = P(t(9)>4.072) = 0.0014$. Como el p-valor es menor que el nivel de significación $\alpha = 0.05$, se rechaza la hipótesis nula y se concluye que el aditivo es efectivo.
:::

:::{#exr-contraste-proporcion-consumo-alcohol}
En un estudio sobre el consumo de alcohol entre los jóvenes durante los fines de semana, se preguntó a 100 chicos y a
125 chicas, de los que 63 chicos y 59 chicas contestaron que consumían.
En vista de estos datos, ¿existe alguna diferencia significativa entre las proporciones de chicos y chicas que consumen alcohol los fines de semana?

:::{.callout-tip collapse="true"}
## Solución

Sea $X_H\sim B(63,p_H)$ la variable aleatoria que mide el número de chicos que consumen alcohol durante los fines de semana en una muestra de tamaño $63$ y $X_M\sim B(59,p_M)$ la variable aleatoria que mide el número de chicas que consumen alcohol durante los fines de semana en una muestra de tamaño $59$. La hipótesis nula es $H_0: p_H=p_M$ y la hipótesis alternativa es $H_1: p_H\neq p_M$. 

Utilizando el contraste de comparación de proporciones, el estadístico de contraste es $z=2.4026$ y el p-valor es $p =2 P(Z>2.4026) = 0.0163$. Como el p-valor es menor que el nivel de significación $\alpha = 0.1$, se rechaza la hipótesis nula y se concluye que hay diferencias significativas entre el consumo de alcohol de chicos y chicas.
:::

:::{#exr-contraste-medias-ingresos}
Se ha realizado un estudio para comparar los ingresos medios de las personas de dos ciudades. Para ello, se ha tomado una muestra de $100$ personas en una ciudad y $120$ en la otra. En la primera ciudad se ha observado una media de $1630$ € mensuales y una cuasidesviación típica de $150$ €, mientras que en la segunda ciudad se ha observado una media de $1780$€ y una cuasidesviación típica de $160$ €. ¿Existen diferencias significativas entre los ingresos medios de las personas de las dos ciudades? Calcular el intervalo de confianza del $95$% para la diferencia entre los ingresos medios.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X_1\sim N(\mu_1, \sigma_1)$ la variable aleatoria que mide los
ingresos mensuales de las personas en la primera ciudad y
$X_2\sim N(\mu_2, \sigma_2)$ la variable aleatoria que mide los
ingresos mensuales de las personas en la segunda ciudad.

Planteamos las hipótesis $H_0: \mu_1=\mu_2$ y $H_1: \mu_1\neq \mu_2$. Para poder utilizar el contraste de la t de student para la comparación de medias en dos poblaciones independientes, primero necesitamos contrastar la igualdad de varianzas mediante el contraste F. El estadístico del contraste es $F=0.879$ y el p-valor es $p =2 P(F(99,119)<0.8789) = 0.508$. Como el p-valor es mayor que el nivel de significación $\alpha = 0.05$, no se rechaza la hipótesis nula y se puede asumir que las varianzas son iguales.

Aplicando el contraste de la t de student para la comparación de medias en dos poblaciones independientes con varianzas iguales, el estadístico de contraste, la cuasidesviación típica ponderada es $\hat s_p = 155.5384$, el estadístico del contraste es $t= -7.123$ y el p-valor es $p =2 P(t(218)<-7.123) = 7.5\cdot 10^{-12}$. Como el p-valor es menor que el nivel de significación $\alpha = 0.05$, se rechaza la hipótesis nula y se concluye que hay diferencias significativas entre los ingresos medios de las personas de las dos ciudades.

El intervalo de confianza del $95$% para la diferencia entre los ingresos medios es $(-191.51, -108.49)$.
:::



:::{#exr-contraste-medias-cigarros}
Para ver si la ley antitabaco está influyendo en el número de cigarros que se fuman mientras se está en los bares se seleccionó una muestra en la que se midió el número de cigarros fumados por hora mientras se estaba en un bar antes de la entrada en vigor de la ley y otra muestra distinta en la que también se midió el número de cigarros fumados por hora después de la entrada en vigor de la ley (se entiende que con la ley en vigor los cigarros se fuman en el exterior de los bares). Los resultados aparecen en la siguientes tablas:

::: {.columns}
::: {.column}
Antes
$$
\begin{array}{cc}
\hline
\mbox{Cigarros} & \mbox{Personas} \\
0-1 & 12\\
1-2 & 21\\
2-3 & 20\\
3-4 & 8\\
\hline
\end{array}
$$
:::
::: {.column}
Después
$$
\begin{array}{cc}
\hline
\mbox{Cigarros} & \mbox{Personas} \\
0-1 & 22\\
1-2 & 18\\
2-3 & 8\\
3-4 & 4\\
\hline
\end{array}
$$
:::
:::

a.  Calcular el intervalo de confianza del $99$% para el número medio de cigarros fumados por hora en los bares antes de la entrada en vigor de la ley. ¿Cuántos individuos serían necesarios para poder estimar dicha media con un margen de error no mayor de $\pm 0.1$ cigarros por hora?

a.  Contrastar si la nueva ley ha reducido significativamente el consumo medio de tabaco en los bares. ¿Cuánto vale el $p$-valor del contraste?
:::

:::{.callout-tip collapse="true"}
## Solución
Sean $X$ e $Y$ las variables que miden el número medio de cigarros fumados por hora antes y después de la entrada en vigor de la ley respectivamente.

a.  Puesto que se trata de una muestra grande de $n_x=61$, la fórmula del intervalo de confianza para la media es

    $$
    \bar x \pm z_{\alpha/2}\frac{\hat s}{\sqrt n}.
    $$

    A partir de la tabla de frecuencias se calculan los estadísticos necesarios:

    \begin{align*}
    \bar x &= \frac{\sum x_in_i}{n_x} = \frac{0.5\cdot12+\cdots+3.5\cdot8}{61} = \frac{115.5}{61} = 1.8934,\\
    s_x^2 & = \frac{\sum x_i^2n_i}{n_x}-\bar x^2 = \frac{0.5^2\cdot12+\cdots+3.5^2\cdot8}{61} -1.8934^2= \frac{273.25}{61}-3.585 = 0.8944,\\
    \hat s_x^2 &= \frac{n_x}{n_x-1}s_x^2 = \frac{61}{60}0.8944 = 0.9093,\\
    \hat s_x & = \sqrt{0.9093} = 0.9536.
    \end{align*}

    Como se pide un nivel de confianza del $99\%$ se tiene que $\alpha=0.01$ y $\alpha/2=0.005$, de modo que buscando en la tabla de la función de distribución de la normal estándar se tiene que $z_{\alpha/2} =2.5758$. Así pues, sustituyendo en la fórmula del intervalo se obtiene

    $$
    \bar x \pm z_{\alpha/2}\frac{\hat s}{\sqrt n} = 1.8934 \pm 2.5758\frac{0.9536}{\sqrt{61}} = 1.8934\pm 0.3145 = (1.5789,\,2.2079).
    $$

    Por otro lado, el número de individuos necesario para estimar la media con un margen de error no mayor de $\pm 0.1$ cigarros por hora y una confianza del $99\%$ es

    $$
    n = \frac{4 z_{\alpha/2}^2 \hat s^2}{A^2} = \frac{4\cdot 2.5758^2 \cdot 0.9093}{(2\cdot 0.1)^2} = 603.2974,
    $$

    es decir, se necesitarían como mínimo $603$ individuos. 

a.  Para contrastar si la nueva ley ha reducido significativamente el consumo medio de tabaco en los bares hay que realizar un contraste unilateral de comparación de medias

    \begin{align*}
    H_0 &: \mu_x = \mu_y\\
    H_1 &: \mu_x > \mu_y
    \end{align*}

    Como los tamaños muestrales son grandes, $n_x=61$ y $n_y=52$, y no se conocen las varianzas poblacionales, el estadístico de contraste es

    $$
    Z = \frac{\bar x -\bar y}{\sqrt{\frac{\hat s_x^2}{n_x}+\frac{\hat s_y^2}{n_y}}},
    $$

    que sigue una distribución normal estándar.

    Para calcularlo se necesitan, además de los estadísticos de $X$ calculados en el apartado anterior, los estadísticos de $Y$, que son:

    \begin{align*}
    \bar y &= \frac{\sum y_jn_j}{n_y} = \frac{0.5\cdot22+\cdots+3.5\cdot4}{52} = \frac{72}{52} = 1.3846,\\
    s_y^2 & = \frac{\sum y_j^2n_j}{n_y}-\bar y^2 = \frac{0.5^2\cdot22+\cdots+3.5^2\cdot4}{52} -1.3846^2= \frac{145}{52}-1.9171 = 0.8713,\\
    \hat s_y^2 &= \frac{n_y}{n_y-1}s_y^2 = \frac{52}{51}0.8713 = 0.8884,\\
    \end{align*}

    de manera que sustituyendo en la fórmula del estadístico de contraste se obtiene

    $$
    Z = \frac{\bar x -\bar y}{\sqrt{\frac{\hat s_x^2}{n_x}+\frac{\hat s_y^2}{n_y}}} 
    = \frac{1.8934-1.3846}{\sqrt{\frac{0.9093}{61}+\frac{0.8884}{52}}} = 2.8447.
    $$

    Como el estadístico sigue una distribución normal estándar, la región de aceptación para un nivel de significación $\alpha=0.05$ es $Z\leq z_\alpha=1.6449$, y como el estadístico cae fuera de esta región se rechaza la hipótesis nula y se concluye que hay pruebas significativas de que la nueva ley ha reducido el consumo medio de tabaco en los bares.

    Finalmente, el $p$-valor del contraste es 
    
    $$
    P(Z>2.8447)= 1- P(Z\leq 2.8447) = 1 - F(2.8447) = 0.0022.
    $$
:::

:::{#exr-contraste-medias-ventas}
Para ver si una campaña de publicidad sobre un fármaco ha influido en
sus ventas, se tomó una muestra de $8$ farmacias y se midió el número
de fármacos vendidos durante un mes, antes y después de la campaña,
obteniéndose los siguientes resultados:

$$
\begin{array}{lcccccccc}
\hline
\mbox{Antes} & 147 & 163 & 121 & 205 & 132 & 190 & 176 & 147  \\
\mbox{Después} & 150 & 171 & 132 & 208 & 141 & 184 & 182 & 145  \\
\hline
\end{array}
$$

Realizar un contraste de hipótesis para comprobar si la campaña de publicidad ha aumentado las ventas medias.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X$ la variable aleatoria que mide la diferencia entre el número
de fármacos vendidos en una farmacia en un mes después y antes de la
campaña de publicidad.

Planteamos las hipótesis $H_0: \mu = 0$ y $H_1: \mu>0$. Utilizando el
contraste de la t de student para la una media poblacional, el estadístico del contraste es $t=1.965$ y el p-valor es $p = P(t(7)>1.965) = 0.045$. Como el p-valor es menor que el nivel de significación $\alpha = 0.05$, se rechaza la hipótesis nula y se concluye que hay pruebas significativas de que la campaña de publicidad ha aumentado las ventas.
:::

:::{#exr-contraste-proporciones-voto}
En una encuesta sobre la intención de voto un partido político, se han tomado dos muestra de $1000$ personas en dos ciudades $A$ y $B$. En la ciudad $A$ se han obtenido $350$ votos a favor del partido y en la ciudad $B$ se han obtenido $390$ votos a favor del partido. ¿Existen diferencias significativas entre las proporciones de votos a favor del partido en las dos ciudades?
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $X_A\sim B(1000,p_A)$ la variable aleatoria que mide el número de votos a favor del partido en la ciudad $A$ y $X_B\sim B(1000,p_B)$ la variable aleatoria que mide el número de votos a favor del partido en la ciudad $B$. 

La hipótesis nula es $H_0: p_A=p_B$ y la hipótesis alternativa es $H_1: p_A\neq p_B$. Utilizando el contraste para la comparación de dos poblaciones, se tiene que el estadístico de contraste es $z=-1.853$ y el p-valor es $p =2 P(Z<-1.853) = 0.0639$. Como el p-valor es mayor que el nivel de significación $\alpha = 0.05$, no se rechaza la hipótesis nula y se concluye que no hay diferencias significativas entre las proporciones de votos a favor del partido en las dos ciudades.
:::